#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

import platform_linuxbsd_builders

common_linuxbsd = [
    "crash_handler_linuxbsd.cpp",
    "os_linuxbsd.cpp",
    "godot_linuxbsd.cpp",
]

# zym: x11/, wayland/, speechd, fontconfig, dbus subdirs and optional
# UI/input/font/TTS dependencies were removed. The CLI is headless: no
# DisplayServer, no system fonts, no TTS, no D-Bus glue.

if env["library_type"] == "static_library":
    prog = env.add_library("#bin/godot", common_linuxbsd)
elif env["library_type"] == "shared_library":
    prog = env.add_shared_library("#bin/godot", common_linuxbsd)
else:
    prog = env.add_program("#bin/godot", common_linuxbsd)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, env.Run(platform_linuxbsd_builders.make_debug_linuxbsd))
